"""empty message

Revision ID: 2241e74af3ba
Revises: 58e873df7fdf
Create Date: 2023-01-19 18:24:16.530515

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2241e74af3ba'
down_revision = '58e873df7fdf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_usuario')
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.Integer(), autoincrement=True, nullable=False))
        batch_op.alter_column('matricula',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.alter_column('matricula',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.drop_column('id')

    op.create_table('_alembic_tmp_usuario',
    sa.Column('nome', sa.VARCHAR(length=100), nullable=True),
    sa.Column('matricula', sa.VARCHAR(length=100), nullable=True),
    sa.Column('email', sa.VARCHAR(length=100), nullable=True),
    sa.Column('senha', sa.VARCHAR(length=100), nullable=True),
    sa.Column('admin', sa.BOOLEAN(), nullable=True),
    sa.Column('id', sa.INTEGER(), nullable=False)
    )
    # ### end Alembic commands ###
