"""Criando tabela demanda

Revision ID: 364e154ab35c
Revises: 50703e0567c1
Create Date: 2023-01-18 18:49:44.258332

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '364e154ab35c'
down_revision = '50703e0567c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('demanda',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('materia', sa.String(length=100), nullable=True),
    sa.Column('requistos', sa.Text(), nullable=True),
    sa.Column('vagas_matutino', sa.Float(), nullable=True),
    sa.Column('vagas_vespertino', sa.Float(), nullable=True),
    sa.Column('vagas_noturno', sa.Float(), nullable=True),
    sa.Column('vagas_flexivel', sa.Float(), nullable=True),
    sa.Column('bolsas_matutino', sa.Float(), nullable=True),
    sa.Column('bolsas_vespertino', sa.Float(), nullable=True),
    sa.Column('bolsas_noturno', sa.Float(), nullable=True),
    sa.Column('bolsas_flexivel', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('demanda')
    # ### end Alembic commands ###
