"""Adicionando campo admin na tabela Usuario

Revision ID: 5bac55f5eaee
Revises: ccc716fef749
Create Date: 2023-01-18 01:53:14.205229

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5bac55f5eaee'
down_revision = 'ccc716fef749'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('admin', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.drop_column('admin')

    # ### end Alembic commands ###
