"""corrigindo requisitos

Revision ID: c4d41a14a212
Revises: 99a4f4335124
Create Date: 2023-01-24 18:49:29.436073

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4d41a14a212'
down_revision = '99a4f4335124'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('demanda', schema=None) as batch_op:
        batch_op.add_column(sa.Column('requisitos', sa.Text(), nullable=True))
        batch_op.drop_column('requistos')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('demanda', schema=None) as batch_op:
        batch_op.add_column(sa.Column('requistos', sa.TEXT(), nullable=True))
        batch_op.drop_column('requisitos')

    # ### end Alembic commands ###
